services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        environment:
            PHP_FPM_LISTEN: 9000
        # Устанавливаем расширения для Laravel и SQLite
        entrypoint: >
            sh -c "
              apt-get update &&
              apt-get install -y libsqlite3-dev zip unzip git &&
              docker-php-ext-install pdo pdo_sqlite &&
              composer install &&
              php-fpm
            "
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
